### ISSUE TITLE
Cable Cover Foul on V1.8

### ISSUE THREAD

**Issue by Makhaira** [VoronDesign/Voron-Afterburner#108]
I've just assembled the CW2 plus SB on a V1.8 MGN12 build. When facing the printer from the front, approximately 6mm of travel is lost from the X axis due to the cable cover fouling on the XY joint.

The point of the foul is around the attachment screw. The cover itself fouls, however removing it still results in a foul as the securing screw for the cover then impacts the XY joint.

Easy fix: A 6mm block is added to the underside of the X gantry which allows the X endstop switch to be triggered. The printer therefore is fully working, but 6mm of travel is lost.

Complicated fix: The cable cover and securing screw position requires moving to avoid this foul.

**Comment by raymondh2** [comment]
Voron 1.8 is considered a legacy printer now. As such development might not account for it

**Comment by Makhaira** [comment]
Absolutely get that, recognise that Trident is the current offering in that family now. Given the high number of 1.8s in the wild though would it not be worth considering it?

With the joys of written communication don't take this as me being argumentative, just challenging if the user base is large enough to warrant consideration, even with it being legacy.

**Comment by raymondh2** [comment]
The number of V1.8 printers built is tiny compared to the other printers we are supporting.

**Comment by wile-e1** [comment]
> Absolutely get that, recognise that Trident is the current offering in that family now. Given the high number of 1.8s in the wild though would it not be worth considering it?
> 
> With the joys of written communication don't take this as me being argumentative, just challenging if the user base is large enough to warrant consideration, even with it being legacy.

This was already discussed in the Stealthburner channel after you brought it up and a definitive answer was already given.

1.8 is no longer a current model which means it may or may not be supported.  There were a lot of 2.1 and 2.2's out in the wild as well, but those models were not considered either because 2.4 is the current version.

I will not be making any changes to the design, but once we hit release.....CAD will also be released and someone will most likely come out with a modification for 1.8.
