### ISSUE TITLE
Cable space has exposed gear and cables would often "click" misleading to extruder clicking

### ISSUE THREAD

**Issue by elcrni** [VoronDesign/Voron-Afterburner#60]
As the title says, i have cramped all cables under cable cover, looks great but i ALWAYS have a cable touching extruder gear and clicking, often thinking its extruder clicking...

**Comment by wile-e1** [comment]
The gear is exposed in order to manually feed filament through the extruder.  Covering this gear would be a major loss of functionality.  The 50T gear is slightly recessed though, so it should just be a matter for re-adjusting the wiring to fit better and have the wiring perpendicular to the slot/opening.
